[project]
name = "hash-ai-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pzierahn", email = "patrick.zierahn@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "elasticsearch>=9.5.0",
    "ipykernel>=7.3.0",
    "requests>=2.34.2",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["recruit"]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
]
